[package]
name = "timertool-rs"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"
default-run = "timerset"

[[bin]]
name = "timerset"
path = "src/main.rs"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.winapi]
git = "https://github.com/OtaK/winapi-rs.git"
branch = "nttimers"
features = ["nttimer", "minwindef", "ntdef"]
